defaults:
  - models: svc.yaml
  - datasets: data.yaml
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .

train_test_split:
  test_size: 0.3
  random_state: 0

GridSearchCV:
  scoring: 'accuracy'
  cv: 5


