export MLFLOW_TRACKING_URI=http://localhost:5000

sklearn_experiment:
	python sklearn_experiment.py

xgb_experiment:
	python xgb_experiment.py

xgb_monitor:
	python xgb_monitor.py

xgb_train:
	python xgb_train.py

lr_train:
	python lr_train.py